
image: maven:3.8.1-openjdk-11

  
build-windows:
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  tags:
    - docker
  script: 
    - mvn -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository clean install -Pwindows -Dno-native-profile
  artifacts:
    name: "PDFOver (Windows) on $CI_COMMIT_REF_SLUG"
    paths:
      - "pdf-over-build/pdf-over_windows.zip"
    expire_in: 1 day # gitlab does not apply this to the latest successful run, only previous runs


