
image: maven:3.8.5-openjdk-17

  
build-windows:
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  tags:
    - docker
  script: 
    - mvn -B -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository clean install -Pwindows -Dno-native-profile
  artifacts:
    name: "PDFOver (Windows) on $CI_COMMIT_REF_SLUG"
    paths:
      - "pdf-over-build/*"
    expire_in: 1 day # gitlab does not apply this to the latest successful run, only previous runs

build-linux:
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  tags:
    - docker
  script: 
    - mvn -B -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository clean install -Plinux -Dno-native-profile
  artifacts:
    name: "PDFOver (Linux) on $CI_COMMIT_REF_SLUG"
    paths:
      - "pdf-over-build/*"
    expire_in: 1 day
    
build-mac:
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  tags:
    - docker
  script: 
    - mvn -B -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository clean install -Pmac -Dno-native-profile
  artifacts:
    name: "PDFOver (Mac) on $CI_COMMIT_REF_SLUG"
    paths:
      - "pdf-over-build/*"
    expire_in: 1 day

build-mac-aarch64:
  stage: build
  cache:
    key: "maven-$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository
  tags:
    - docker
  script: 
    - mvn -B -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository clean install -Pmac-aarch64 -Dno-native-profile
  artifacts:
    name: "PDFOver (Mac M1) on $CI_COMMIT_REF_SLUG"
    paths:
      - "pdf-over-build/*"
    expire_in: 1 day
