{
  "formatVersion": "1.1",
  "component": {
    "group": "at.gv.egiz.pdfas",
    "module": "pdf-as-lib",
    "version": "4.2.1-snapshot",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "p64czxgonrdlfnrjffin6iyvja"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "at.gv.egiz.pdfas",
          "module": "pdf-as-common",
          "version": {
            "requires": "4.2.1-snapshot"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.13"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.68"
          }
        },
        {
          "group": "javax.activation",
          "module": "activation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.7.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "ognl",
          "module": "ognl",
          "version": {
            "requires": "3.2.19"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "javase",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "pdf-as-lib-4.2.1-snapshot.jar",
          "url": "pdf-as-lib-4.2.1-snapshot.jar",
          "size": 1540758,
          "sha512": "b2003cbb2de568da31c4e1c6c1c9f0ab76a56da03b9d4acb05b1ef80849567afbb7de530f092699cc64d2141cf438f5d55bc539e2a8d25274c84eae4ae5f25f2",
          "sha256": "1666b54e971e8100f1f4b8fed0dc1709f901b6ac344521c4f94d0f7594cc4c2c",
          "sha1": "3f83a637908fa8b588a9fcb9befdc93f16ea2ede",
          "md5": "68f109f2dd818ec3cf7ab68a5700ab41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "at.gv.egiz.pdfas",
          "module": "pdf-as-common",
          "version": {
            "requires": "4.2.1-snapshot"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpmime",
          "version": {
            "requires": "4.5.13"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk15on",
          "version": {
            "requires": "1.68"
          }
        },
        {
          "group": "javax.activation",
          "module": "activation",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "javax.xml.bind",
          "module": "jaxb-api",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "org.bitbucket.b_c",
          "module": "jose4j",
          "version": {
            "requires": "0.7.6"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8"
          }
        },
        {
          "group": "org.glassfish.jaxb",
          "module": "jaxb-runtime",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-collections4",
          "version": {
            "requires": "4.4"
          }
        },
        {
          "group": "ognl",
          "module": "ognl",
          "version": {
            "requires": "3.2.19"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.slf4j",
          "module": "jcl-over-slf4j",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.4.1"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "javase",
          "version": {
            "requires": "3.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "pdf-as-lib-4.2.1-snapshot.jar",
          "url": "pdf-as-lib-4.2.1-snapshot.jar",
          "size": 1540758,
          "sha512": "b2003cbb2de568da31c4e1c6c1c9f0ab76a56da03b9d4acb05b1ef80849567afbb7de530f092699cc64d2141cf438f5d55bc539e2a8d25274c84eae4ae5f25f2",
          "sha256": "1666b54e971e8100f1f4b8fed0dc1709f901b6ac344521c4f94d0f7594cc4c2c",
          "sha1": "3f83a637908fa8b588a9fcb9befdc93f16ea2ede",
          "md5": "68f109f2dd818ec3cf7ab68a5700ab41"
        }
      ]
    }
  ]
}
