name: Build Windows Package
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install -Pwindows -Dno-native-profile
      - name: Describe current commit
        run: echo "commit_sha=$("${{ github.sha }}".SubString(0,7))" >> $env:GITHUB_ENV
      - name: Remove Previous Build Artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.issue;
            (await github.rest.actions.listArtifactsForRepo({ owner, repo })).data.artifacts
              .filter(({ name }) => (name.startsWith('pdf-over-${{ github.ref_name }}-') && name.endsWith('windows-x86_64')))
              .forEach(({ id, name }) => { console.log('Deleting '+name+' ('+id+')'); github.rest.actions.deleteArtifact({ owner, repo, artifact_id: id }); });
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-over-${{ github.ref_name }}-${{ env.commit_sha }}-windows-x86_64
          path: pdf-over-build/pdf-over_windows-x86_64.zip

permissions:
    contents: read
    actions: write
