name: Build Linux Package
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install -Plinux -Dno-native-profile
      - name: Describe current commit
        run: echo "commit_sha=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Remove Previous Build Artifacts
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.issue;
            (await github.rest.actions.listArtifactsForRepo({ owner, repo })).data.artifacts
              .filter(({ name }) => (name.startsWith('pdf-over-${{ github.ref_name }}-') && name.endsWith('linux-x86_64')))
              .forEach(({ id, name }) => { console.log('Deleting '+name+' ('+id+')'); github.rest.actions.deleteArtifact({ owner, repo, artifact_id: id }); });
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdf-over-${{ github.ref_name }}-${{ env.commit_sha }}-linux-x86_64
          path: pdf-over-build/pdf-over_linux-x86_64.jar

permissions:
    contents: read
    actions: write
